insert into products (productId, name, price, description, image, stock, categoryId) values (15, 'Wine - Mondavi Coastal Private', 804.68, 'Wine - Mondavi Coastal Private', '4.JPG', 1, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (16, 'Flower - Commercial Spider', 625.14, 'Flower - Commercial Spider', '1.JPG', 2, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (17, 'Molasses - Fancy', 604.7, 'Molasses - Fancy', '4.JPG', 3, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (18, 'Lettuce - Romaine, Heart', 499.1, 'Lettuce - Romaine, Heart', '3.jJPG', 4, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (19, 'Shrimp - Black Tiger 26/30', 474.15, 'Shrimp - Black Tiger 26/30', '2.JPG', 5, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (20, 'Tofu - Soft', 827.58, 'Tofu - Soft', '4.JPG', 6, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (21, 'Seedlings - Clamshell', 176.55, 'Seedlings - Clamshell', '1.JPG', 7, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (22, 'Veal - Leg', 844.22, 'Veal - Leg', '2.JPG', 8, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (23, 'Soup Campbells', 342.22, 'Soup Campbells', '1.JPG', 9, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (24, 'Couscous', 794.41, 'Couscous', '3.jJPG', 10, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (25, 'Sauce - Apple, Unsweetened', 517.49, 'Sauce - Apple, Unsweetened', '2.JPG', 11, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (26, 'Onions - White', 659.43, 'Onions - White', '3.jJPG', 12, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (27, 'Bag - Clear 7 Lb', 272.53, 'Bag - Clear 7 Lb', '1.JPG', 13, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (28, 'Energy Drink - Franks Pineapple', 438.93, 'Energy Drink - Franks Pineapple', '4.JPG', 14, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (29, 'Clementine', 136.38, 'Clementine', '1.JPG', 15, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (30, 'Ice Cream Bar - Drumstick', 4.87, 'Ice Cream Bar - Drumstick', '4.JPG', 16, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (31, 'Juice - Grapefruit, 341 Ml', 416.47, 'Juice - Grapefruit, 341 Ml', '3.jJPG', 17, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (32, 'Beef - Outside, Round', 694.89, 'Beef - Outside, Round', '4.JPG', 18, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (33, 'Turkey - Breast, Double', 220.36, 'Turkey - Breast, Double', '3.jJPG', 19, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (34, 'Oil - Shortening - All - Purpose', 196.51, 'Oil - Shortening - All - Purpose', '4.JPG', 20, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (35, 'Asparagus - Frozen', 429.65, 'Asparagus - Frozen', '2.JPG', 21, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (36, 'Basil - Seedlings Cookstown', 971.58, 'Basil - Seedlings Cookstown', '4.JPG', 22, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (37, 'Langers - Cranberry Cocktail', 617.52, 'Langers - Cranberry Cocktail', '4.JPG', 23, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (38, 'Lemons', 856.41, 'Lemons', '3.jJPG', 24, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (39, 'Nantucket - Orange Mango Cktl', 907.21, 'Nantucket - Orange Mango Cktl', '1.JPG', 25, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (40, 'Tea - Herbal Orange Spice', 492.6, 'Tea - Herbal Orange Spice', '3.jJPG', 26, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (41, 'Skirt - 24 Foot', 519.14, 'Skirt - 24 Foot', '2.JPG', 27, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (42, 'Venison - Denver Leg Boneless', 971.51, 'Venison - Denver Leg Boneless', '4.JPG', 28, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (43, 'Beef Wellington', 1027.49, 'Beef Wellington', '3.jJPG', 29, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (44, 'Pepper - Yellow Bell', 229.45, 'Pepper - Yellow Bell', '2.JPG', 30, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (45, 'Bread Roll Foccacia', 833.0, 'Bread Roll Foccacia', '3.jJPG', 31, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (46, 'Wine - Chardonnay South', 3.91, 'Wine - Chardonnay South', '3.jJPG', 32, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (47, 'Latex Rubber Gloves Size 9', 364.06, 'Latex Rubber Gloves Size 9', '4.JPG', 33, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (48, 'Chocolate - Milk', 675.67, 'Chocolate - Milk', '3.jJPG', 34, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (49, 'Ginger - Pickled', 293.06, 'Ginger - Pickled', '2.JPG', 35, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (50, 'Fish - Soup Base, Bouillon', 165.87, 'Fish - Soup Base, Bouillon', '4.JPG', 36, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (51, 'Artichokes - Jerusalem', 20.5, 'Artichokes - Jerusalem', '3.jJPG', 37, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (52, 'Bread Base - Italian', 638.12, 'Bread Base - Italian', '2.JPG', 38, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (53, 'Beef - Ground Medium', 690.53, 'Beef - Ground Medium', '2.JPG', 39, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (54, 'Juice - Lagoon Mango', 900.35, 'Juice - Lagoon Mango', '1.JPG', 40, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (55, 'Tuna - Salad Premix', 835.62, 'Tuna - Salad Premix', '4.JPG', 41, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (56, 'Mudslide', 955.53, 'Mudslide', '3.jJPG', 42, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (57, 'Pork - Belly Fresh', 539.11, 'Pork - Belly Fresh', '1.JPG', 43, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (58, 'Mushroom - Enoki, Dry', 624.95, 'Mushroom - Enoki, Dry', '1.JPG', 44, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (59, 'Pastry - Apple Large', 972.56, 'Pastry - Apple Large', '1.JPG', 45, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (60, 'Doilies - 10, Paper', 168.58, 'Doilies - 10, Paper', '3.jJPG', 46, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (61, 'Flour - Fast / Rapid', 376.34, 'Flour - Fast / Rapid', '3.jJPG', 47, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (62, 'Coffee - Dark Roast', 362.93, 'Coffee - Dark Roast', '4.JPG', 48, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (63, 'Salmon - Smoked, Sliced', 441.43, 'Salmon - Smoked, Sliced', '2.JPG', 49, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (64, 'Extract - Lemon', 424.77, 'Extract - Lemon', '3.jJPG', 50, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (65, 'Sauce - Marinara', 59.63, 'Sauce - Marinara', '1.JPG', 51, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (66, 'Veal - Loin', 402.27, 'Veal - Loin', '2.JPG', 52, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (67, 'Veal - Nuckle', 433.52, 'Veal - Nuckle', '4.JPG', 53, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (68, 'Lamb - Loin, Trimmed, Boneless', 351.74, 'Lamb - Loin, Trimmed, Boneless', '4.JPG', 54, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (69, 'Daikon Radish', 270.29, 'Daikon Radish', '2.JPG', 55, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (70, 'Nestea - Ice Tea, Diet', 1037.52, 'Nestea - Ice Tea, Diet', '2.JPG', 56, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (71, 'Bread - Olive Dinner Roll', 847.83, 'Bread - Olive Dinner Roll', '3.jJPG', 57, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (72, 'Lobster - Tail, 3 - 4 Oz', 247.03, 'Lobster - Tail, 3 - 4 Oz', '1.JPG', 58, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (73, 'Pickle - Dill', 47.49, 'Pickle - Dill', '2.JPG', 59, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (74, 'Wine - Chianti Classica Docg', 296.03, 'Wine - Chianti Classica Docg', '4.JPG', 60, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (75, 'Chicken Breast Wing On', 626.53, 'Chicken Breast Wing On', '3.jJPG', 61, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (76, 'Peas - Frozen', 69.8, 'Peas - Frozen', '3.jJPG', 62, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (77, 'Cheese - Marble', 255.47, 'Cheese - Marble', '3.jJPG', 63, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (78, 'Beer - Blue', 230.8, 'Beer - Blue', '1.JPG', 64, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (79, 'Beef - Rib Roast, Capless', 958.41, 'Beef - Rib Roast, Capless', '1.JPG', 65, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (80, 'Lamb Tenderloin Nz Fr', 339.13, 'Lamb Tenderloin Nz Fr', '3.jJPG', 66, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (81, 'Crush - Orange, 355ml', 585.12, 'Crush - Orange, 355ml', '4.JPG', 67, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (82, 'Roe - Lump Fish, Red', 637.49, 'Roe - Lump Fish, Red', '3.jJPG', 68, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (83, 'Cheese - Cheddar, Medium', 762.98, 'Cheese - Cheddar, Medium', '3.jJPG', 69, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (84, 'Fish - Atlantic Salmon, Cold', 116.15, 'Fish - Atlantic Salmon, Cold', '3.jJPG', 70, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (85, 'Pepper - Julienne, Frozen', 843.2, 'Pepper - Julienne, Frozen', '2.JPG', 71, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (86, 'Cookies Almond Hazelnut', 284.23, 'Cookies Almond Hazelnut', '2.JPG', 72, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (87, 'Extract - Vanilla,artificial', 18.41, 'Extract - Vanilla,artificial', '1.JPG', 73, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (88, 'Jello - Assorted', 233.46, 'Jello - Assorted', '1.JPG', 74, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (89, 'Sparkling Wine - Rose, Freixenet', 118.85, 'Sparkling Wine - Rose, Freixenet', '3.jJPG', 75, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (90, 'Energy Drink - Franks Original', 600.02, 'Energy Drink - Franks Original', '2.JPG', 76, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (91, 'Cheese - Havarti, Salsa', 469.98, 'Cheese - Havarti, Salsa', '4.JPG', 77, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (92, 'Extract - Almond', 320.16, 'Extract - Almond', '3.jJPG', 78, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (93, 'Lemon Pepper', 276.28, 'Lemon Pepper', '4.JPG', 79, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (94, 'Fish - Base, Bouillion', 852.33, 'Fish - Base, Bouillion', '1.JPG', 80, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (95, 'Pork - Tenderloin, Frozen', 718.02, 'Pork - Tenderloin, Frozen', '2.JPG', 81, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (96, 'Cheese - Mozzarella', 598.25, 'Cheese - Mozzarella', '4.JPG', 82, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (97, 'Soup - Cream Of Broccoli, Dry', 309.85, 'Soup - Cream Of Broccoli, Dry', '4.JPG', 83, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (98, 'Puree - Mocha', 1031.39, 'Puree - Mocha', '2.JPG', 84, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (99, 'Halibut - Fletches', 897.37, 'Halibut - Fletches', '2.JPG', 85, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (100, 'Hersey Shakes', 902.32, 'Hersey Shakes', '4.JPG', 86, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (101, 'Bread - Olive Dinner Roll', 802.13, 'Bread - Olive Dinner Roll', '2.JPG', 87, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (102, 'Shopper Bag - S - 4', 812.33, 'Shopper Bag - S - 4', '3.jJPG', 88, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (103, 'Wine - Beaujolais Villages', 382.98, 'Wine - Beaujolais Villages', '4.JPG', 89, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (104, 'Bread - Roll, Canadian Dinner', 1021.71, 'Bread - Roll, Canadian Dinner', '3.jJPG', 90, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (105, 'Wine - Sogrape Mateus Rose', 929.67, 'Wine - Sogrape Mateus Rose', '1.JPG', 91, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (106, 'Arctic Char - Fresh, Whole', 333.73, 'Arctic Char - Fresh, Whole', '3.jJPG', 92, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (107, 'Glycerine', 463.57, 'Glycerine', '2.JPG', 93, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (108, 'Lettuce - Romaine, Heart', 65.63, 'Lettuce - Romaine, Heart', '1.JPG', 94, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (109, 'Dc - Sakura Fu', 763.59, 'Dc - Sakura Fu', '3.jJPG', 95, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (110, 'V8 - Tropical Blend', 330.84, 'V8 - Tropical Blend', '1.JPG', 96, 3);
insert into products (productId, name, price, description, image, stock, categoryId) values (111, 'Soup - Cream Of Potato / Leek', 461.28, 'Soup - Cream Of Potato / Leek', '1.JPG', 97, 4);
insert into products (productId, name, price, description, image, stock, categoryId) values (112, 'Pepper - Pablano', 170.17, 'Pepper - Pablano', '4.JPG', 98, 1);
insert into products (productId, name, price, description, image, stock, categoryId) values (113, 'Onions - Pearl', 855.99, 'Onions - Pearl', '4.JPG', 99, 2);
insert into products (productId, name, price, description, image, stock, categoryId) values (114, 'Crab - Back Fin Meat, Canned', 915.25, 'Crab - Back Fin Meat, Canned', '2.JPG', 100, 2);
